### ISSUE TITLE
php problems in ver 1.04

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/simplenews#10]
Still php problems:

_Notice: Undefined property: stdClass::$langcode i SimplenewsSourceNode->getLanguage() (linje 570 af /home/buddhistisk/bd.buddhistisksamfund.dk/modules/simplenews/includes/simplenews.source.inc)._

Using php v. 7.4

-and all new mail rejected as spam (but that might be a different problem).

**Comment by Egmund** [comment]
Would it be a 'solution' for me to edit the database to change 'language' from 'und' to actual languagecode like 'da' in 'simplenews_subscriber'?

**Comment by indigoxela** [comment]
> Would it be a 'solution' for me to edit the database to change 'language' ...

I don't think so, no. The problem seems to be caused by some language/langcode naming mixup in a property or variable (I'm not currently using simplenews, so can't test).

**Comment by Egmund** [comment]
I will await some debugging then.
Are there other newsletter modules for BD?

**Comment by Egmund** [comment]
Another thing. The (chrone?) system keeps trying to send the refused mail event though I have unpublished the newsletter. How do I stop that?

**Comment by olafgrabienski** [comment]
This issue reminds https://github.com/backdrop-contrib/simplenews/issues/7, see also the [commit with the fix](https://github.com/backdrop-contrib/simplenews/commit/0c2ca230568ce4d1e2d88bc495dcb8e05b5ab230) which changes `langcode` to `language` in several places.

**Comment by Egmund** [comment]
But isn't that fix included in latest version? I checked the files - it is!

**Comment by olafgrabienski** [comment]
> keeps trying to send the refused mail event though I have unpublished the newsletter

I think, the only option is to change the sending status in the database. I don't know the exact steps, but it must be something like described in https://www.drupal.org/project/simplenews/issues/1271242. That said, be careful with editing the database directly.

**Comment by Egmund** [comment]
I unchecked the 'use chron' and set mail spool expiration to 'immediate'.  Hopefully that works.

**Comment by olafgrabienski** [comment]
> But isn't that fix included in latest version? I checked the files - it is!

Okay, but the file reported in your message (`simplenews/includes/simplenews.source.inc`) doesn't seem to be part of the fix.

**Comment by indigoxela** [comment]
> But isn't that fix included in latest version? I checked the files - it is!

My current suspicion: the fix did too much. At least one of those "langcode" might have been correct and broke now.

Or maybe ... the fix was still incomplete?

**Comment by Egmund** [comment]
I wouldn't know which instances of langcode to replace.
At this point it most likely only generate a line in the log file. The spam issue is more serious. I will have to dive into that one.
Thank you both for the comments.

**Comment by indigoxela** [comment]
> The spam issue is more serious.

That's for sure unrelated to the log message. Try some tool like https://www.mail-tester.com/ to figure out what's problematic.

> I wouldn't know which instances of langcode to replace.

Hopefully someone will figure out.

**Comment by Egmund** [comment]
Actually this error is more serious. I get error sending mail. Mail is not send.

**Comment by indigoxela** [comment]
> Actually this error is more serious. I get error sending mail. Mail is not send.

But didn't you just try to turn sending off?

As you're struggling with spam recognition, there must have been successful mail delivery before, no?

**Comment by Egmund** [comment]
I created a new newsletter, tried to send it to mail-tester, but it never left the mailserver. Maybe the sending mailserver have some weird spam-filter. I have contacted my host.
I think a few got through initially but only to addresses on the same mailserver.

I get several php errorlines and then a final line saying 0 mail send in 0.6 seconds.
Let us see what my host say - when he get to it. There was a server crash right after I started with this newsletter, so maybe this is related.

**Comment by Egmund** [comment]
Also, I have send newsletter before with no problems - as far as I know - maybe before v. 1.04

**Comment by alanmels** [comment]
Just seeing this. Sorry for late processing, but @Egmund could you please try to narrow this ticket to one specific problem (as it seems to be discussing different issues) and give exact steps on how to replicate it? Feel free to create new issues, but always try to report one specific problem in each issue. Thanks.

**Comment by alanmels** [comment]
The initially reported problem with _Undefined property_ should be fixed by https://github.com/backdrop-contrib/simplenews/commit/aad300e6cce7f005676f0760db9d484f3b5ff121

**Comment by Egmund** [comment]
Thank you @alanmels for taking time with this.
I ignored the language warning - seems 'merely' to be a 'message'.
The issue seems to have been a temporary problem on the mail server - having issues sending bulk mail.
So: Solved it seems.
