### ISSUE TITLE
How to send HTML mails?

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/simplenews#11]
I've tried using SMTP authentication, MIME mail and PHPmailer module but sinplenews mails won't be formatted as HTML. In the same site there are Webform mails which are sent as formatted HTML mails.

**Comment by alanmels** [comment]
Have you changed _Format_ on admin/config/services/simplenews/settings from _Plain_ to _HTML_?

**Comment by djzwerg** [comment]
@alanmels yes

**Comment by alanmels** [comment]
I think you are missing the Mail System module. Please install the https://github.com/backdrop-contrib/mailsystem module, go to `/admin/config/system/mailsystem` and make sure _Mime Mail_ is selected for _Site-wide default mail system_. Let me know if it worked or not.

**Comment by djzwerg** [comment]
I've done this before opening this issue. MIME Mail is there and selected as described.

**Comment by alanmels** [comment]
Pardon, the link was supposed to be for the _mailsystem_ module.

**Comment by djzwerg** [comment]
I've installed the mail system, too. But that doesn't solve it 😕

**Comment by alanmels** [comment]
I've just tested this on a fresh Backdrop site with Mail System, Mime Mail and Simplenews and it is sending messages in HTML format as expected, so you must be missing something. 

Can you go to `admin/config/services/simplenews` and make sure your individual newsletters are set to HTML?

Not general setting on `/admin/config/services/simplenews/settings`, but setting for an individual newsletter such as `/admin/config/services/simplenews/categories/1/edit`.

**Comment by djzwerg** [comment]
You're right! That was what I've missed. Thanks a lot!
