### ISSUE TITLE
How to deal with paragraph items?

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/simplenews#17]
Hi. I recognized that the behavior of sent mails differs if you are using paragraphs within the nodes.

Examples:

- a file attachment paragraph to the node won't be an attachment to the mail (if you want it as an attached file to the newsletter mail you have to use a file field).
- a leaflet map paragraph is a blanc area in the mail (not tested with a Geofield node field yet)

Are there any plans to improve the support of paragraphs?

**Comment by alanmels** [comment]
@djzwerg, thanks for reporting this issue. 

Quick search is giving this issue on DO https://www.drupal.org/project/simplenews/issues/2848816, so maybe you want to check the permissions. If it doesn't resolve the issue, please note the module was ported from Drupal 7 version as is, therefore you need to verify if D7 Simplenews supported paragraph. If it does not, then I am afraid you would have to either come up with PR or wait for at least couple months just as other issues have to (see https://github.com/backdrop-contrib/simplenews/issues/16).

**Comment by djzwerg** [comment]
@alanmels thanks for your fast reply. The permissions are OK - images were shown in the sent mails.

This issue should not have high priority because using core fields is working fine.

**Comment by djzwerg** [comment]
@alanmels would it be possible to add a notice to the readme file like "Paragraph items are currently not supported"?

**Comment by alanmels** [comment]
Please make sure your paragraphs are embedded as running a test I couldn't replicate the problem. I mean all paragraph fields are sent successfully as a newsletter. If you want to display some kind of custom field value, then you have to change your template file accordingly (see https://github.com/backdrop-contrib/simplenews/issues/26).
 
![Screenshot 2024-03-26 at 12 19 12 AM](https://github.com/backdrop-contrib/simplenews/assets/56604405/9d838f68-d2a0-4c9f-b5cc-44df74e5fa69)
