### ISSUE TITLE
Node newsletter page (node/NID/simplenews) doesn't reflect "Sent" status

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/simplenews#20]
When a newsletter is sent, its status isn't releflected on the page `node/NID/newsletter`. Therefore, you can send a newsletter multiple times.

Steps to reproduce:

- On a vanilla Backdrop site, install and enable Simplenews.
- Create a Simplenews newsletter (`node/add/simplenews`).
- Change to the _Newsletter_ tab of the node, e.g. `node/6/simplenews`, enable the option "Send newsletter", and hit the _Send_ button. As a result, you see the message "Newsletter Test letter 2 pending."
- Check the page `admin/content/simplenews`. The "Sent" status of the newsletter is `0`.
- Run cron, and check `admin/content/simplenews` again. The "Sent" status is `√`, i.e. "Sent".
- (added, see [comment below](https://github.com/backdrop-contrib/simplenews/issues/20#issuecomment-1421006353)) Be sure to not clear the caches in the meantime.
- Go back to the _Newsletter_ tab of the node.

**Actual result:** There is no "Sent" message on the node Newsletter page, and you can send the newsletter again.

**Expected result:** Hide the Send form, and show the message "This newsletter has been sent".

**Comment by olafgrabienski** [comment]
I guess, the relevant code is around line https://github.com/backdrop-contrib/simplenews/blob/a8274501cde6364b918fadfb54702eeed6ed4cd7/includes/simplenews.admin.inc#L1939

In the Backdrop version of Simplenews, the sending options of a Newsletter issue are shown always, no matter what the Send status is. Maybe `$simplenews_values->status` doesn't work correctly?

Backdrop:
`if ($simplenews_values->status == SIMPLENEWS_STATUS_SEND_NOT || ...`

Drupal 7:
`if ($status == SIMPLENEWS_STATUS_SEND_NOT || ...`

**Comment by olafgrabienski** [comment]
An update: I've tested some more times. Sometimes I was able to reproduce the issue, sometimes not.

As far as I can tell, the Newsletter page behaves as expected after sending a newsletter, when you have cleared the caches. In this case, the Send form is hidden, and you see the message "This newsletter has been sent". Otherwise, you will be able to send the newsletter twice (which is a bad idea). I'll update the issue description re cache.

**Comment by alanmels** [comment]
@olafgrabienski, thanks for the report. I'm sorry, but I'm superbusy these days, so this has to wait. I'd welcome any PR or co-maintaining requests as apparently the module needs lots of further improvements.

**Comment by argiepiano** [comment]
I've tested - as suspected it is a node cache issue. Unlike D7, Backdrop uses entity cache for nodes by default, meaning that, unless you clear caches, loading a node will load it from the cached version (which will contain an old version of the `simplenews` object, with the wrong status).

There are several options about how to deal with this. I've checked several of them, and the most efficient is clearing the node cache ONLY for the simplenews nodes, inside `simplenews_send_status_update()`. This function is called right after the newsletter is emailed, and is called by all methods (cron or immediate sending).  It's not called, however, when you email a test. So this is the expected behavior.

PR coming in a minute. Please test....

**Comment by argiepiano** [comment]
@olafgrabienski, please see PR #21. Please test with different types of sending methods.

To clarify: this modification clears the db-stored node entity cache. The caching provided by Simplenews is static memory cache (not disk cache), so this modification will not interfere with any of the provided caching.

**Comment by argiepiano** [comment]
Actually, this PR needs some work - the cache clearing should happen also when the newsletter is spooled to be sent by cron. Right now, the "pending" status is not shown when using that method of sending, unless you manually clear the cache. 

I'll modify the PR later tonight.

**Comment by argiepiano** [comment]
PR fixed. The node cache is now cleared upon submission of the form (which catches the "pending" status), and also after the newsletters are actually sent (which catches the updated status from pending to sent). Please test.

**Comment by olafgrabienski** [comment]
Many thanks for your help! PR tested, works perfectly. I've checked the various sending options (send test mail, send mails using cron, send mails immediately), and all work as expected.

**Comment by argiepiano** [comment]
Great! I'm not a maintainer, so probably @alanmels or someone else will need to merge this.

**Comment by alanmels** [comment]
@olafgrabienski, thank you for spotting this issue. @argiepiano, thank you for your time to getting this fixed. PR has been merged.
