### ISSUE TITLE
Problem transferring config between environments

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/simplenews#22]
Great module, working nicely for me thank you.

I have seen an error message that is preventing me from transferring config from dev to staging environments.

The message is:

Configuration sync failed. The following errors were reported:
The configuration "simplenews.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.

The Simplenews module is installed on both sites, and functioning on both. I got around this error (which prevents config import) by copying the relevant config files manually with ftp.

Is this a bug?

**Comment by yorkshire-pudding** [comment]
@nattywebdev - there you go, a pull request, are you able to test?
@alanmels - FYI

**Comment by nattywebdev** [comment]
Tested and now works fine - thank you.

**Comment by alanmels** [comment]
Thank you @nattywebdev for reporting the issue and @yorkshire-pudding - for fixing it. Because of time deficiency I had to push the fix without testing trusting @yorkshire-pudding did test.
