### ISSUE TITLE
PHP 8 compatibility - Creation of dynamic property

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/simplenews#24]
When sending a test-newsletter, I got:

```
    Deprecated function: Creation of dynamic property SimplenewsSourceNode::$uid is deprecated in SimplenewsSourceNode->setContext() (line 612 of .../modules/simplenews/includes/simplenews.source.inc).
    Deprecated function: Creation of dynamic property SimplenewsSourceNode::$original_language is deprecated in SimplenewsSourceNode->setContext() (line 620 of .../modules/simplenews/includes/simplenews.source.inc).
```

To fix it, there should be definitions for both properties in class SimplenewsSourceNode:

```
  protected $uid;// or maybe "public"?
  protected $original_language;
```
Note, I'm not actually familiar with simplenews, just saw this when testing something. (AKA don't wait for my PR, just go ahead and fix it). :wink:

**Comment by alanmels** [comment]
Thanks for reporting. Even-though I could not replicate the issue sending multiple test newsletters, I trust your judgement and will be adding both definitions.
