### ISSUE TITLE
Personalised emails: adding subscriber name from user account

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/simplenews#26]
Is it possible to add the first name of the corresponding user account as a token into the email message?
I see that $simplenews_subscriber is known to the template, but can I pull such info from the corresponding user account? In my site this is a user account field called field_user_first_name - and all subscribers will have a user account.

**Comment by alanmels** [comment]
This is not a Simplenews letter specific issue, but more of a Backdrop question, because you can manipulate variables in any theme template. For example, you can use:

```php
$addressee = user_load($simplenews_subscriber->uid);
print $addressee->field_user_first_name[LANGUAGE_NONE][0]['value'];
```

**Comment by nattywebdev** [comment]
Thank you @alanmels - I can confirm this works perfectly.
