### ISSUE TITLE
PHP notices on `admin/people/simplenews`

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/simplenews#7]
On the *Newsletter subscriptions* list on `admin/people/simplenews`, I see a lot of PHP notices, i.e. the very same PHP notice for every subscription:

> Notice: Undefined property: stdClass::$langcode in simplenews_subscription_list_form() (line 1169 of /my-path/modules/simplenews/includes/simplenews.admin.inc).

This is the line in question: https://github.com/backdrop-contrib/simplenews/blob/1.x-1.x/includes/simplenews.admin.inc#L1169

When I edit a subscription item, I'm not able choose a "Preferred language" – the select list is empty.

**Comment by alanmels** [comment]
What PHP-version you are using?

**Comment by olafgrabienski** [comment]
Hi Alan, the PHP version is `7.4.28`.

In case it matters, this happens on a multilingual site with two languages (English is not the default).

**Comment by alanmels** [comment]
Let me run some tests and come back to this later...

**Comment by alanmels** [comment]
The update is ready, however even-though I'm listed as the maintainer for the module, for some reason I can't push any code. Do you know how I could re-gain the maintainer privileges over this module?

**Comment by olafgrabienski** [comment]
Thanks for working on it so quick! Re repository permissions, that happens sometimes, and asking for help in Zulip is the best way to handle it. I saw you already did that, so let's just wait. (For me it's not urgent to apply the fix.)

**Comment by olafgrabienski** [comment]
Many thanks for the update! I've just tested the new release, and the PHP notices on `admin/people/simplenews` don't appear anymore.

However, the reported problem of the empty "Preferred language" remains:

> When I edit a subscription item, I'm not able choose a "Preferred language" – the select list is empty.

Now I see, there is also a couple of PHP notices and warnings on the edit page:

- Notice: Undefined offset: 1 in simplenews_subscriptions_admin_form() (line 796 of my-path/modules/simplenews/includes/simplenews.subscription.inc).
- Warning: Invalid argument supplied for foreach() in simplenews_subscriptions_admin_form() (line 796 of my-path/modules/simplenews/includes/simplenews.subscription.inc).
- Notice: Undefined variable: language_options in simplenews_subscriptions_admin_form() (line 819 of my-path/modules/simplenews/includes/simplenews.subscription.inc).
- Warning: Invalid argument supplied for foreach() in form_select_options() (line 2873 of my-path/core/includes/form.inc).

Should I open a new issue for it?

**Comment by alanmels** [comment]
Olaf, thank you for testing the new version. Let's re-open this ticket, however note I won't have time to troubleshoot this soon. So it has to wait until someone else offers PR or the war in Ukraine is over (relevant to my calendar).

**Comment by alanmels** [comment]
Olaf, we haven't used Simplenews on any of multi-language sites for now, so never extensively tested it for language-related issues. Please give a try to the latest dev version and let me know if the problems reported persist for you.

**Comment by olafgrabienski** [comment]
@alanmels Thanks for working on the issue! I've just downloaded https://github.com/backdrop-contrib/simplenews/archive/refs/heads/1.x-1.x.zip and put it on my test site. Now, when I go to `admin/people/simplenews`, I get a white screen and the following PHP error:

> Failed opening required 'my-path/modules/simplenews/includes/simplenews.admin.inc' (include_path='.:/usr/share/php:..') in system_block_view() (line 2559 of my-path/core/modules/system/system.module).

**Comment by alanmels** [comment]
Well, the file is there https://github.com/backdrop-contrib/simplenews/tree/1.x-1.x/includes Can you check if the`simplenews.admin.inc` is there intact on your setup?

**Comment by olafgrabienski** [comment]
Yes, the file was there. So I cleared all caches and tried it once more, and then the error disappeared.

Also, the remaining problem reported in https://github.com/backdrop-contrib/simplenews/issues/7#issuecomment-1094654522 is fixed: When I edit a subscription item, now I *am* able to choose a "Preferred language". Thank you again!

**Comment by alanmels** [comment]
Glad, it's working for you. So I'm marking this as closed then.
