### ISSUE TITLE
It should at least prevent people from subscribing the same e-mail twice until a confirmation has been received

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/simplenews#9]
The title is a part of the quote from https://beamtic.com/gmail-and-unsolicited-mail :

> The offending site was a Drupal-based website with a simplenews module. The problem with simplenews seems to be that it does nothing to verify that the submission is valid. As a minimum, it should at least prevent people from subscribing the same e-mail twice until a confirmation has been received; instead it appears to just repeatedly send the same e-mail over and over whenever someone submits it through the subscription form.

We have to check and if this is true then to fix it.

**Comment by olafgrabienski** [comment]
> We have to check and if this is true then to fix it.

@alanmels Just tested (with a newsletter configured to use the double opt-in method): Simplenews sends the same confirmation mail twice if you subscribe two times with the same email address to a newsletter. This is the confirmation mail I got twice:

> We have received a request to subscribe test@example.com to the Example
Newsletter newsletter on Example website at
https://example.com/. To confirm please use the link
below.
> 
> https://example.com/newsletter/confirm/add/LONG-ID

**Comment by alanmels** [comment]
@olafgrabienski, thank you for testing. Unfortunately, no time, so this was just hammering a peg. Will have to wait. Or someone could offer a PR.

**Comment by alanmels** [comment]
I've pushed just partial progress, there is more to come, so re-opening.
